export const Ingredients = [
  "Salt",
  "Pepper",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Butter",
  "Sugar",
  "Flour",
  "Eggs",
  "Milk",
  "Tomatoes",
  "Lemon",
  "Chicken",
  "Beef",
  "Pasta",
  "Rice",
  "Potatoes",
  "Carrots",
  "Bell Pepper",
  "Bread",
  "Parmesan Cheese",
  "Basil",
  "Thyme",
  "Rosemary",
  "Cumin",
  "Paprika",
  "Chili Powder",
  "Soy Sauce",
  "Vinegar",
  "Honey",
  "Ginger",
  "Cinnamon",
  "Nutmeg",
  "Vanilla Extract",
  "Cocoa Powder",
  "Cream",
  "Yogurt",
  "Cheese",
  "Spinach",
  "Broccoli",
  "Mushrooms",
  "Cilantro",
  "Parsley",
  "Oregano",
  "Bay Leaves",
  "Lime",
  "Cayenne Pepper",
  "Coriander",
  "Mustard",
  "Ketchup",
  "Mayonnaise",
  "Worcestershire Sauce",
  "Pineapple",
  "Avocado",
  "Tuna",
  "Salmon",
  "Shrimp",
  "Lettuce",
  "Green Beans",
  "Zucchini",
  "Black Beans",
  "Chickpeas",
  "Kidney Beans",
  "Cabbage",
  "Cucumber",
  "Peanut Butter",
  "Walnuts",
  "Almonds",
  "Cashews",
  "Pecans",
  "Coconut Milk",
  "Tofu",
  "Quinoa",
  "Brown Rice",
  "Panko Breadcrumbs",
  "Cayenne Pepper",
  "Turmeric",
  "Cloves",
  "Cardamom",
  "Parsnip",
  "Rutabaga",
  "Eggplant",
  "Ground Pork",
  "Ground Lamb",
  "Ground Turkey",
  "Ground Veal",
  "Lamb Chops",
  "Salami",
  "Chorizo",
  "Couscous",
  "Sesame Oil",
  "Balsamic Vinegar",
  "Red Wine",
  "White Wine",
  "Champagne",
  "Red Bell Pepper",
  "Yellow Bell Pepper",
  "Green Bell Pepper",
  "Artichoke",
  "Capers",
  "Peaches",
  "Apples",
  "Bananas",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Oranges",
  "Grapes",
  "Lemons",
  "Limes",
  "Cherries",
  "Pears",
  "Mangoes",
  "Kiwi",
  "Pineapples",
  "Plums",
  "Watermelon",
  "Cantaloupe",
  "Honeydew Melon",
  "Coconut",
  "Raisins",
  "Prunes",
  "Figs",
  "Dates",
  "Cranberries",
  "Blackberries",
  "Pomegranate",
  "Apricots",
  "Rhubarb",
  "Goat Cheese",
  "Blue Cheese",
  "Brie Cheese",
  "Cheddar Cheese",
  "Mozzarella Cheese",
  "Parmesan Cheese",
  "Swiss Cheese",
  "Gouda Cheese",
  "Provolone Cheese",
  "Feta Cheese",
  "Bleu Cheese",
  "Camembert Cheese",
  "Gruyere Cheese",
  "Monterey Jack Cheese",
  "Pepper Jack Cheese",
  "Havarti Cheese",
  "Colby Cheese",
  "Muenster Cheese",
  "Limburger Cheese",
  "Roquefort Cheese",
  "Edam Cheese",
  "Emmental Cheese",
  "Fontina Cheese",
  "Jarlsberg Cheese",
  "Manchego Cheese",
  "Port Wine Cheese",
  "Stilton Cheese",
  "Ginger",
  "Turmeric",
  "Cayenne Pepper",
  "Cardamom",
  "Cumin",
  "Coriander",
  "Paprika",
  "Nutmeg",
  "Cloves",
  "Allspice",
  "Vanilla Extract",
  "Almond Extract",
  "Peppermint Extract",
  "Lemon Extract",
  "Orange Extract",
  "Rum Extract",
  "Maple Extract",
  "Coconut Extract",
  "Rosewater",
  "Orange Blossom Water",
  "Lavender Extract",
  "Anise Extract",
  "Lemon Zest",
  "Orange Zest",
  "Lime Zest",
  "Lemon Juice",
  "Lime Juice",
  "Orange Juice",
  "Grapefruit Juice",
  "Cranberry Juice",
  "Pineapple Juice",
  "Tomato Juice",
  "Apple Juice",
  "Pomegranate Juice",
  "Mango Juice",
  "Passion Fruit Juice",
  "Peach Juice",
  "Cherry Juice",
  "Blackberry Juice",
  "Raspberry Juice",
  "Strawberry Juice",
  "Blueberry Juice",
  "Cucumber Juice",
  "Carrot Juice",
  "Beet Juice",
  "Celery Juice",
  "Kale Juice",
  "Spinach Juice",
  "Wheatgrass Juice",
  "Aloe Vera Juice",
  "Coconut Water",
  "Seltzer Water",
  "Tonic Water",
  "Ginger Ale",
  "Root Beer",
  "Cola",
  "Lemon-Lime Soda",
  "Orange Soda",
  "Grape Soda",
  "Cherry Soda",
  "Cream Soda",
  "Dr. Pepper",
  "Mountain Dew",
  "Pepsi",
  "Coca-Cola",
  "Sprite",
  "7UP",
  "Club Soda",
  "Gin",
  "Vodka",
  "Rum",
  "Tequila",
  "Whiskey",
  "Scotch",
  "Brandy",
  "Cointreau",
  "Triple Sec",
  "Campari",
  "Vermouth",
  "Kahlúa",
  "Baileys Irish Cream",
  "Grand Marnier",
  "Amaretto",
  "Midori",
  "Sambuca",
  "Frangelico",
  "Chambord",
  "Peach Schnapps",
  "Creme de Menthe",
  "Creme de Cassis",
  "Blue Curacao",
  "Aperol",
  "Chartreuse",
  "Pernod",
  "Absinthe",
  "Jagermeister",
  "Sloe Gin",
  "Raspberry Liqueur",
  "Butterscotch Schnapps",
  "Benedictine",
  "Maraschino Liqueur",
  "Schnapps",
  "Brandy",
  "Cognac",
  "Aquavit",
  "Sake",
  "Sherry",
  "Port Wine",
  "Madeira Wine",
  "Marsala Wine",
  "Vermouth",
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio",
  "Cabernet Sauvignon",
  "Merlot",
  "Syrah",
  "Zinfandel",
  "Malbec",
  "Tempranillo",
  "Grenache",
  "Champagne",
  "Protein Powder",
  "Prosecco",
  "Sparkling Wine",
  "Rose Wine",
  "White Wine",
  "Red Wine",
  "Beer",
  "Ale",
  "Lager",
  "Stout",
  "Pilsner",
  "IPA",
  "Porter",
  "Wheat Beer",
  "Sour Beer",
  "Hard Cider",
  "Sake",
  "Tea",
  "Coffee",
  "Espresso",
  "Cappuccino",
  "Latte",
  "Mocha",
  "Chai Tea",
  "Green Tea",
  "Black Tea",
  "Oolong Tea",
  "White Tea",
  "Herbal Tea",
  "Rooibos Tea",
  "Mint Tea",
  "Lavender Tea",
  "Chamomile Tea",
  "Ginger Tea",
  "Honey Tea",
  "Lemon Tea",
  "Orange Tea",
  "Cinnamon Tea",
  "Spices (various, including various blends)",
  "Herbs (various, including various blends)",
  "Eggplant",
  "Kale",
  "Radish",
  "Turnip",
  "Collard Greens",
  "Okra",
  "Fennel",
  "Leek",
  "Chives",
  "Scallions",
  "Shallots",
  "Artichoke",
  "Brussels Sprouts",
  "Beets",
  "Rutabaga",
  "Parsnips",
  "Zucchini",
  "Squash",
  "Pumpkin",
  "Escarole",
  "Endive",
  "Watercress",
  "Arugula",
  "Kohlrabi",
  "Jicama",
  "Daikon Radish",
  "Bok Choy",
  "Napa Cabbage",
  "Chinese Cabbage",
  "Swiss Chard",
  "Turnip Greens",
  "Mustard Greens",
  "Rhubarb",
  "Chard",
  "Habanero Pepper",
  "Ghost Pepper",
  "Serrano Pepper",
  "Jalapeño Pepper",
  "Poblano Pepper",
  "Anaheim Pepper",
  "Bell Pepper",
  "Banana Pepper",
  "Cubanelle Pepper",
  "Green Chili Pepper",
  "Red Chili Pepper",
  "Chipotle Pepper",
  "Cayenne Pepper",
  "Tabasco Pepper",
  "Thai Chili Pepper",
  "Pimento Pepper",
  "Long Pepper",
  "White Pepper",
  "Black Pepper",
  "Pink Peppercorn",
  "Lemon Pepper",
  "Garlic Pepper",
  "Onion Powder",
  "Garlic Powder",
  "Cinnamon Stick",
  "Vanilla Bean",
  "Saffron",
  "Tarragon",
  "Dill",
  "Bay Leaf",
  "Nigella Seeds",
  "Fenugreek",
  "Sesame Seeds",
  "Poppy Seeds",
  "Caraway Seeds",
  "Fennel Seeds",
  "Mustard Seeds",
  "Cumin Seeds",
  "Coriander Seeds",
  "Celery Seeds",
  "Cardamom Pods",
  "Star Anise",
  "Juniper Berries",
  "Allspice Berries",
  "Szechuan Peppercorns",
  "Garam Masala",
  "Curry Powder",
  "Turmeric Powder",
  "Pumpkin Pie Spice",
  "Apple Pie Spice",
  "Chinese Five Spice",
  "Herbes de Provence",
  "Italian Seasoning",
  "Poultry Seasoning",
  "Old Bay Seasoning",
  "Creole Seasoning",
  "Taco Seasoning",
  "Ranch Dressing Mix",
  "French Onion Soup Mix",
  "Horseradish",
  "Soy Milk",
  "Almond Milk",
  "Cashew Milk",
  "Rice Milk",
  "Coconut Cream",
  "Evaporated Milk",
  "Sweetened Condensed Milk",
  "Whipped Cream",
  "Mascarpone Cheese",
  "Cream Cheese",
  "Sour Cream",
  "Greek Yogurt",
  "Cottage Cheese",
  "Ricotta Cheese",
  "Gouda Cheese",
  "Brie Cheese",
  "Camembert Cheese",
  "Gruyere Cheese",
  "Monterey Jack Cheese",
  "Pepper Jack Cheese",
  "Colby Cheese",
  "Muenster Cheese",
  "Limburger Cheese",
  "Roquefort Cheese",
  "Edam Cheese",
  "Emmental Cheese",
  "Fontina Cheese",
  "Jarlsberg Cheese",
  "Manchego Cheese",
  "Port Wine Cheese",
  "Stilton Cheese",
  "Ginger",
  "Turmeric",
  "Cayenne Pepper",
  "Cardamom",
  "Cumin",
  "Coriander",
  "Paprika",
  "Nutmeg",
  "Cloves",
  "Allspice",
  "Vanilla Extract",
  "Almond Extract",
  "Peppermint Extract",
  "Lemon Extract",
  "Orange Extract",
  "Rum Extract",
  "Maple Extract",
  "Coconut Extract",
  "Rosewater",
  "Orange Blossom Water",
  "Lavender Extract",
  "Anise Extract",
  "Lemon Zest",
  "Orange Zest",
  "Lime Zest",
  "Lemon Juice",
  "Lime Juice",
  "Orange Juice",
  "Grapefruit Juice",
  "Cranberry Juice",
  "Pineapple Juice",
  "Tomato Juice",
  "Apple Juice",
  "Pomegranate Juice",
  "Mango Juice",
  "Passion Fruit Juice",
  "Peach Juice",
  "Cherry Juice",
  "Blackberry Juice",
  "Raspberry Juice",
  "Strawberry Juice",
  "Blueberry Juice",
  "Cucumber Juice",
  "Carrot Juice",
  "Beet Juice",
  "Celery Juice",
  "Kale Juice",
  "Spinach Juice",
  "Wheatgrass Juice",
  "Aloe Vera Juice",
  "Coconut Water",
  "Seltzer Water",
  "Tonic Water",
  "Ginger Ale",
  "Root Beer",
  "Cola",
  "Lemon-Lime Soda",
  "Orange Soda",
  "Grape Soda",
  "Cherry Soda",
  "Cream Soda",
  "Dr. Pepper",
  "Mountain Dew",
  "Pepsi",
  "Coca-Cola",
  "Sprite",
  "7UP",
  "Club Soda",
  "Gin",
  "Vodka",
  "Rum",
  "Tequila",
  "Whiskey",
  "Scotch",
  "Brandy",
  "Cointreau",
  "Triple Sec",
  "Campari",
  "Vermouth",
  "Kahlúa",
  "Baileys Irish Cream",
  "Grand Marnier",
  "Amaretto",
  "Midori",
  "Sambuca",
  "Frangelico",
  "Chambord",
  "Peach Schnapps",
  "Creme de Menthe",
  "Creme de Cassis",
  "Blue Curacao",
  "Aperol",
  "Chartreuse",
  "Pernod",
  "Absinthe",
  "Jagermeister",
  "Sloe Gin",
  "Raspberry Liqueur",
  "Butterscotch Schnapps",
  "Benedictine",
  "Maraschino Liqueur",
  "Schnapps",
  "Brandy",
  "Cognac",
  "Aquavit",
  "Sake",
  "Sherry",
  "Port Wine",
  "Madeira Wine",
  "Marsala Wine",
  "Vermouth",
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio",
  "Cabernet Sauvignon",
  "Merlot",
  "Syrah",
  "Zinfandel",
  "Malbec",
  "Tempranillo",
  "Grenache",
  "Champagne",
  "Prosecco",
  "Sparkling Wine",
  "Rose Wine",
  "White Wine",
  "Red Wine",
  "Beer",
  "Ale",
  "Lager",
  "Stout",
  "Pilsner",
  "IPA",
  "Porter",
  "Wheat Beer",
  "Sour Beer",
  "Hard Cider",
  "Sake",
  "Tea",
  "Coffee",
  "Espresso",
  "Cappuccino",
  "Latte",
  "Mocha",
  "Chai Tea",
  "Green Tea",
  "Black Tea",
  "Oolong Tea",
  "White Tea",
  "Herbal Tea",
  "Rooibos Tea",
  "Mint Tea",
  "Lavender Tea",
  "Chamomile Tea",
  "Ginger Tea",
  "Honey Tea",
  "Lemon Tea",
  "Orange Tea",
  "Cinnamon Tea",
];
